ju_riby_projects:
    path:     /{project}
    defaults: { _controller: JuRibyBundle:Default:projects, project: 0 }
ju_riby_a_propos:
    path:     /a_propos/
    defaults: { _controller: JuRibyBundle:Default:aPropos }
ju_riby_contact:
    path:     /contact/
    defaults: { _controller: JuRibyBundle:Default:contact }

