ju_riby_homepage:
    path:     /
    defaults: { _controller: JuRibyBundle:Default:homepage }
ju_riby_project:
    path:     /project/{project}
    defaults: { _controller: JuRibyBundle:Default:project }
ju_riby_a_propos:
    path:     /a_propos/
    defaults: { _controller: JuRibyBundle:Default:aPropos }
ju_riby_contact:
    path:     /contact/
    defaults: { _controller: JuRibyBundle:Default:contact }

